### ISSUE TITLE
Was not able to make it work

### ISSUE THREAD

**Issue by slimshader** [Cysharp/SlnMerge#1]
I added #.cs file to Editor folder and .mergesettings file in Editor and Assets (was not sure where to put it), after deleting all project files I was no longer able to open c# project from unity as it stopped regenerating but since there is no error message I am not sure what I did wrong

**Comment by mayuki** [comment]
Could you put `.mergesettings` file in the directory same as `.sln` file. (typically, `.sln` file is generated in the root folder of the Unity project). If Unity doesn't regenerate .sln/.csproj files, try restarting Unity.

## Example
- **UnityProject1** (Unity Project)
    - **UnityProject1.sln**
    - **UnityProject1.sln.mergesettings**
    - Assembly-CSharp.csproj
    - Assembly-CSharp-Editor.csproj
    - Assets (Folder)
        - Editor (Folder)
            - **SlnMerge.cs**
    - Library (Folder)
    - ProjectSetttings (Folder)
    - etc ...

**Comment by slimshader** [comment]
This indeed worked and new solution is added to my Unity project, thanks :) Thing is I though I would be able to use merged project within Unity project, for example creating a base class library that I could then use in my MonoBehaviours. Is it not the use case?
