### ISSUE TITLE
Remove duplicates by transitive references

### ISSUE THREAD

**Issue by KuraiAndras** [Cysharp/SlnMerge#3]
I have an issue, which might be an edge case for most people, but is causing some inconvenience when trying this.

I have a project setup: .Net Standard 2.0 library ==> Unity project for common stuff ==> Unity project for desktop

The .net standard library is referenced with the unity package manager(i created an asmdef for the project, then with upm you can add it with a relative file path) by the unity common project, then the desktop project references both the common project and the standard library.

The first unity project in the chain is working perfectly with slnmerge, but on the second one slnmerge duplicates the .net standard library, with both the actual one, and the one created by unity's automatic csproj generator. The problem with this, is that changes made to the standard library (for example renaming classes) breaks both Visual Studio and Resharper functions when changing stuff.

Could you make it so that when the sln is edited projects with the same name don't get both added? If not automatically maybe let it be configured by the merge settings?

**Comment by mayuki** [comment]
How do you refer to `Unity common project` from `Unity project for desktop`?
Sorry, I don't know how to refer to a Unity project from another Unity project.

Could you upload a project to reproduce if possible?

**Comment by KuraiAndras** [comment]
https://github.com/KuraiAndras/UnityReference
I have created an example application for demonstarting this. The last 2 commits add sln merge, the problems are in the description of the commits.

In short: When merging solutions the actual problem is that if some project is referenced from unity with the unity package manager, then generated sln contains both the csproj generated by unity and the original one added by slnmerge are present, whereas the expected output in my opinion would be only adding the original one, and removing the one generated by unity.

**Comment by mayuki** [comment]
Thanks for your cooperation. I could reproduce and understood the problem in that case.
I agree with your opinion that either project was deleted and one was left.

I want to be able to choose which to keep if the Unity generated project and the original project conflict.
